apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-deployment
  labels:
    app: system
spec:
  selector:
    matchLabels:
      app: system
  template:
    metadata:
      labels:
        app: system
    spec:
      containers:
      - name: system-container
        image: default-route-openshift-image-registry.apps-crc.testing/my-project/system:1.0-SNAPSHOT
        ports:
        - containerPort: 9080
--- 
apiVersion: v1
kind: Service
metadata:
  name: system-service
spec:
  selector:
    app: system
  ports:
  - protocol: TCP
    port: 9080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: system-route
spec:
  to:
    kind: Service
    name: system-service